// mux_gating_gate_50.v

// Generated using ACDS version 26.1 110

`timescale 1 ps / 1 ps
module mux_gating_gate_50 (
		input  wire  ena,    //    ena.export, Clock enable of the clock gate block. This signal is active-high.
		input  wire  inclk,  //  inclk.clk,    Input signal to the clock network.
		output wire  outclk  // outclk.clk,    Output of the Clock Control IP core.
	);

	mux_gating_gate_50_intelclkctrl_201_mliac7a mux_gating_gate_50 (
		.ena    (ena),    //   input,  width = 1,    ena.export
		.inclk  (inclk),  //   input,  width = 1,  inclk.clk
		.outclk (outclk)  //  output,  width = 1, outclk.clk
	);

endmodule
