// mux_clock_control.v

// Generated using ACDS version 26.1 110

`timescale 1 ps / 1 ps
module mux_clock_control (
		input  wire  inclk0x,   //   inclk0x.clk,    Input 0 signal to the clock network.
		input  wire  inclk1x,   //   inclk1x.clk,    Input 1 signal to the clock network.
		input  wire  clkselect, // clkselect.export, Input that dynamically selects the clock source to drive the clock network
		output wire  outclk     //    outclk.clk,    Output of the Clock Control IP core.
	);

	mux_clock_control_intelclkctrl_201_o5z5vqy mux_clock_control (
		.inclk0x   (inclk0x),   //   input,  width = 1,   inclk0x.clk
		.inclk1x   (inclk1x),   //   input,  width = 1,   inclk1x.clk
		.clkselect (clkselect), //   input,  width = 1, clkselect.export
		.outclk    (outclk)     //  output,  width = 1,    outclk.clk
	);

endmodule
